[package]
name = "msglib_v2"
version = "0.0.1"

[addresses]
msglib_v2 = "0x1759cc0d3161f1eb79f65847d4feb9d1f74fb79014698a23b16b28b9cd4c37e3"

[dependencies]
layerzero_common = { local = "../../layerzero-common" }
msglib_auth = { local = "../msglib-auth" }
zro = { local = "../../zro" }