[package]
name = "executor_ext"
version = "0.0.1"

[addresses]
executor_ext = "0x1759cc0d3161f1eb79f65847d4feb9d1f74fb79014698a23b16b28b9cd4c37e3"

[dependencies]
AptosFramework = { local = "../../deps/aptos-core/aptos-move/framework/aptos-framework" }
